In [3]:
import numpy as np
m = np.array([[ 0,  1,  2,  3,  4],
           [ 5,  6,  7,  8,  9],
           [10, 11, 12, 13, 14]])

In [4]:
#이 행렬에서 값 7 을 인덱싱한다.
print(m[1,2])
#이 행렬에서 값 14 을 인덱싱한다.
print(m[-1,-1])
#이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
print(m[1,1:3])
#이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
print(m[1:,2])
#이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.
print(m[:2, 3:])

7
14
[6 7]
[ 7 12]
[[3 4]
 [8 9]]


In [9]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
x= x[:,np.newaxis]

In [13]:
x[:,:,np.newaxis]

array([[[0]],

       [[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]],

       [[6]],

       [[7]],

       [[8]],

       [[9]]])

In [20]:
a = np.arange(10)
b = np.arange(5)[:, np.newaxis]
a + b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13]])

In [23]:
np.max((a + b)[1,:])

10

In [30]:
#5 x 6 형태의 데이터 행렬을 만들고 이 데이터에 대해 다음과 같은 값을 구한다.
a = np.arange(5)[:,np.newaxis]
b = np.arange(6)
c = a + b

print(c)

#전체의 최댓값
print(c.max())

#각 행의 합
print(c.sum(axis = 0))

#각 열의 평균
print(c.mean(axis = 1))

[[0 1 2 3 4 5]
 [1 2 3 4 5 6]
 [2 3 4 5 6 7]
 [3 4 5 6 7 8]
 [4 5 6 7 8 9]]
9
[10 15 20 25 30 35]
[ 2.5  3.5  4.5  5.5  6.5]


In [58]:
"""다음 배열은 첫번째 행(row)에 학번, 
두번째 행에 영어 성적, 세번째 행에 수학 성적을 적은 배열이다.
영어 성적을 기준으로 각 열(column)을 재정렬하라.
array([[  1,    2,    3,    4],
       [ 46,   99,  100,   71],
       [ 81,   59,   90,  100]])"""

ar = np.array([[1, 2, 3, 4],
       [46, 99, 100, 71],
       [81, 59, 90, 100]])
a = ar[1,:].argsort()
print(a)
ar[:,a]

[0 3 1 2]


array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])